"""RecLLM Python Core — DOCX Exporter"""

import logging
from pathlib import Path
from datetime import datetime
from dataclasses import dataclass

from app.database.db import get_cursor

logger = logging.getLogger(__name__)


def export_transcript_docx(
    recording_id: str,
    output_path: str | Path,
    include_metadata: bool = True,
    language: str = "ja",
) -> str:
    """Export a transcript to DOCX format.

    Returns the output file path.
    """
    try:
        from docx import Document
        from docx.shared import Pt, Inches, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise RuntimeError("python-docx not installed. Run: pip install python-docx")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Load data
    with get_cursor() as cur:
        cur.execute("SELECT * FROM recordings WHERE id = ?", (recording_id,))
        recording = cur.fetchone()
        if not recording:
            raise ValueError(f"Recording not found: {recording_id}")

        cur.execute(
            "SELECT * FROM utterances WHERE recording_id = ? ORDER BY start_ms",
            (recording_id,),
        )
        utterances = cur.fetchall()

    doc = Document()

    # Title
    title = recording["display_name"] or recording["original_file_name"] or recording_id
    heading = doc.add_heading(title, level=1)

    subtitle = "RecLLM 文字起こしレポート" if language == "ja" else "RecLLM Transcription Report"
    p = doc.add_paragraph(subtitle)
    p.runs[0].font.size = Pt(10)
    p.runs[0].font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    # Metadata
    if include_metadata:
        doc.add_heading("メタデータ" if language == "ja" else "Metadata", level=2)
        table = doc.add_table(rows=0, cols=2)
        table.style = "Light Grid"

        meta_items = []
        if recording["original_file_name"]:
            meta_items.append(("ファイル名" if language == "ja" else "File", recording["original_file_name"]))
        if recording["processed_at"]:
            meta_items.append(("処理日" if language == "ja" else "Processed", recording["processed_at"][:10]))
        if recording["duration_seconds"] and recording["duration_seconds"] > 0:
            h = int(recording["duration_seconds"] // 3600)
            m = int((recording["duration_seconds"] % 3600) // 60)
            meta_items.append(("時間" if language == "ja" else "Duration", f"{h}h {m}m" if h > 0 else f"{m}m"))
        if recording["speaker_count"]:
            meta_items.append(("話者数" if language == "ja" else "Speakers", str(recording["speaker_count"])))
        if recording["language_code"]:
            meta_items.append(("言語" if language == "ja" else "Language", recording["language_code"]))

        for label, value in meta_items:
            row = table.add_row()
            row.cells[0].text = label
            row.cells[1].text = value

    # Transcript
    doc.add_heading("文字起こし" if language == "ja" else "Transcript", level=2)

    for u in utterances:
        ts = _ms_to_ts(u["start_ms"])
        text = u["corrected_text"] or u["text"]
        p = doc.add_paragraph()
        run_ts = p.add_run(f"[{ts}] ")
        run_ts.font.size = Pt(8)
        run_ts.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
        run_speaker = p.add_run(f"{u['speaker']}: ")
        run_speaker.bold = True
        run_speaker.font.size = Pt(10)
        run_text = p.add_run(text)
        run_text.font.size = Pt(10)

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph(f"Generated by RecLLM — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    doc.save(str(output_path))

    # Record export
    with get_cursor() as cur:
        cur.execute(
            "INSERT INTO exports (recording_id, export_type, file_path, include_metadata) VALUES (?, ?, ?, ?)",
            (recording_id, "docx", str(output_path), int(include_metadata)),
        )

    return str(output_path)


def _ms_to_ts(ms: int) -> str:
    total = ms // 1000
    h, remainder = divmod(total, 3600)
    m, s = divmod(remainder, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"
