"""RecLLM Python Core — PDF Exporter with Metadata Block"""

import logging
from pathlib import Path
from datetime import datetime, timezone
from dataclasses import dataclass

from app.database.db import get_cursor

logger = logging.getLogger(__name__)

PDF_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
body {{ font-family: 'Noto Sans JP', 'Hiragino Sans', sans-serif; font-size: 11px; line-height: 1.6; margin: 0; padding: 20mm; color: #1a1a1a; }}
h1 {{ font-size: 18px; margin-bottom: 4px; color: #111; }}
.subtitle {{ font-size: 11px; color: #666; margin-bottom: 16px; }}
.meta-block {{ background: #f8f9fa; border: 1px solid #e9ecef; border-radius: 4px; padding: 12px 16px; margin-bottom: 20px; }}
.meta-row {{ display: flex; justify-content: space-between; padding: 2px 0; font-size: 10px; }}
.meta-label {{ color: #666; min-width: 120px; }}
.meta-value {{ color: #333; font-weight: 500; }}
.section {{ margin-bottom: 16px; }}
.section h2 {{ font-size: 13px; color: #333; border-bottom: 1px solid #dee2e6; padding-bottom: 4px; margin-bottom: 8px; }}
.utterance {{ margin-bottom: 6px; }}
.timestamp {{ color: #6c757d; font-size: 9px; font-family: monospace; }}
.speaker {{ font-weight: 600; color: #495057; }}
.text {{ color: #212529; }}
.summary-block {{ background: #f0f7ff; border-left: 3px solid #0066cc; padding: 10px 14px; margin-bottom: 12px; }}
.list-item {{ margin-bottom: 4px; padding-left: 12px; position: relative; }}
.list-item::before {{ content: "•"; position: absolute; left: 0; color: #666; }}
.footer {{ margin-top: 30px; padding-top: 10px; border-top: 1px solid #dee2e6; font-size: 9px; color: #999; text-align: center; }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="subtitle">{subtitle}</div>

{metadata_block}

{summary_block}

{transcript_block}

<div class="footer">Generated by RecLLM — {generated_at}</div>
</body>
</html>"""


@dataclass
class PdfExportOptions:
    include_metadata: bool = True
    include_summary: bool = True
    include_transcript: bool = True
    include_timestamps: bool = True
    language: str = "ja"


def export_transcript_pdf(
    recording_id: str,
    output_path: str | Path,
    options: PdfExportOptions | None = None,
) -> str:
    """Export a transcript to PDF with metadata and summary.

    Returns the output file path.
    """
    if options is None:
        options = PdfExportOptions()

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Load data
    with get_cursor() as cur:
        cur.execute("SELECT * FROM recordings WHERE id = ?", (recording_id,))
        recording = cur.fetchone()
        if not recording:
            raise ValueError(f"Recording not found: {recording_id}")

        cur.execute(
            "SELECT * FROM utterances WHERE recording_id = ? ORDER BY start_ms",
            (recording_id,),
        )
        utterances = cur.fetchall()

        cur.execute(
            "SELECT * FROM summaries WHERE recording_id = ? ORDER BY generated_at DESC LIMIT 1",
            (recording_id,),
        )
        summary = cur.fetchone()

    # Build HTML
    title = recording["display_name"] or recording["original_file_name"] or recording_id
    subtitle = "RecLLM 文字起こしレポート" if options.language == "ja" else "RecLLM Transcription Report"

    metadata_block = _build_metadata_block(recording, options) if options.include_metadata else ""
    summary_block = _build_summary_block(summary, options) if options.include_summary and summary else ""
    transcript_block = _build_transcript_block(utterances, options) if options.include_transcript else ""

    html = PDF_TEMPLATE.format(
        title=_escape(title),
        subtitle=subtitle,
        metadata_block=metadata_block,
        summary_block=summary_block,
        transcript_block=transcript_block,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
    )

    # Write HTML (for now — WeasyPrint conversion added when dependency is available)
    html_path = output_path.with_suffix(".html")
    html_path.write_text(html, encoding="utf-8")

    # Try PDF conversion
    try:
        from weasyprint import HTML
        HTML(string=html).write_pdf(str(output_path))
    except ImportError:
        # WeasyPrint not available — save as HTML
        logger.warning("WeasyPrint not installed. Saving as HTML instead of PDF.")
        output_path = html_path

    # Record export
    with get_cursor() as cur:
        cur.execute(
            "INSERT INTO exports (recording_id, export_type, file_path, include_metadata) VALUES (?, ?, ?, ?)",
            (recording_id, "pdf", str(output_path), int(options.include_metadata)),
        )

    return str(output_path)


def _build_metadata_block(recording, options: PdfExportOptions) -> str:
    """Build the metadata HTML block."""
    rows = []

    if recording["original_file_name"]:
        rows.append(("ファイル名" if options.language == "ja" else "File", recording["original_file_name"]))

    if recording["recording_date"]:
        rows.append(("録音日" if options.language == "ja" else "Recording Date", recording["recording_date"]))

    if recording["processed_at"]:
        rows.append(("処理日" if options.language == "ja" else "Processed", recording["processed_at"][:10]))

    if recording["duration_seconds"] and recording["duration_seconds"] > 0:
        h = int(recording["duration_seconds"] // 3600)
        m = int((recording["duration_seconds"] % 3600) // 60)
        dur = f"{h}h {m}m" if h > 0 else f"{m}m"
        rows.append(("時間" if options.language == "ja" else "Duration", dur))

    if recording["speaker_count"] and recording["speaker_count"] > 0:
        rows.append(("話者数" if options.language == "ja" else "Speakers", str(recording["speaker_count"])))

    if recording["language_code"]:
        rows.append(("言語" if options.language == "ja" else "Language", recording["language_code"]))

    if recording["noise_reduction"]:
        rows.append(("ノイズ除去" if options.language == "ja" else "Noise Reduction", "適用済み" if options.language == "ja" else "Applied"))

    if recording["model_provider"]:
        provider = recording["model_provider"]
        model = recording["model_name"] or ""
        rows.append(("AIプロバイダー" if options.language == "ja" else "AI Provider", f"{provider}" + (f" / {model}" if model else "")))

    if not rows:
        return ""

    meta_rows = "\n".join(
        f'<div class="meta-row"><span class="meta-label">{_escape(label)}</span><span class="meta-value">{_escape(value)}</span></div>'
        for label, value in rows
    )
    return f'<div class="meta-block">{meta_rows}</div>'


def _build_summary_block(summary, options: PdfExportOptions) -> str:
    """Build the summary HTML block."""
    import json

    parts = []

    if summary["summary"]:
        label = "要約" if options.language == "ja" else "Summary"
        parts.append(f'<div class="section"><h2>{label}</h2><div class="summary-block">{_escape(summary["summary"])}</div></div>')

    point_notes = json.loads(summary["point_notes"] or "[]")
    if point_notes:
        label = "重要ポイント" if options.language == "ja" else "Key Points"
        items = "\n".join(f'<div class="list-item">{_escape(n)}</div>' for n in point_notes)
        parts.append(f'<div class="section"><h2>{label}</h2>{items}</div>')

    action_items = json.loads(summary["action_items"] or "[]")
    if action_items:
        label = "アクション項目" if options.language == "ja" else "Action Items"
        items = "\n".join(f'<div class="list-item">{_escape(n)}</div>' for n in action_items)
        parts.append(f'<div class="section"><h2>{label}</h2>{items}</div>')

    decisions = json.loads(summary["decisions"] or "[]")
    if decisions:
        label = "決定事項" if options.language == "ja" else "Decisions"
        items = "\n".join(f'<div class="list-item">{_escape(n)}</div>' for n in decisions)
        parts.append(f'<div class="section"><h2>{label}</h2>{items}</div>')

    risks = json.loads(summary["risks"] or "[]")
    if risks:
        label = "リスク" if options.language == "ja" else "Risks"
        items = "\n".join(f'<div class="list-item">{_escape(n)}</div>' for n in risks)
        parts.append(f'<div class="section"><h2>{label}</h2>{items}</div>')

    return "\n".join(parts)


def _build_transcript_block(utterances, options: PdfExportOptions) -> str:
    """Build the transcript HTML block."""
    if not utterances:
        return ""

    label = "文字起こし" if options.language == "ja" else "Transcript"
    lines = []

    for u in utterances:
        ts = ""
        if options.include_timestamps:
            ts = f'<span class="timestamp">[{_ms_to_ts(u["start_ms"])}]</span> '
        lines.append(
            f'<div class="utterance">{ts}<span class="speaker">{_escape(u["speaker"])}:</span> '
            f'<span class="text">{_escape(u["corrected_text"] or u["text"])}</span></div>'
        )

    return f'<div class="section"><h2>{label}</h2>{"".join(lines)}</div>'


def _ms_to_ts(ms: int) -> str:
    """Convert ms to HH:MM:SS."""
    total = ms // 1000
    h, remainder = divmod(total, 3600)
    m, s = divmod(remainder, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def _escape(text: str) -> str:
    """HTML-escape text."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
