import { useState, useCallback } from "react";

export interface PdfDraft {
  transcriptId: string;
  headerText: string;
  footerText: string;
  speakerNames: Record<string, string>; // original → display
  speakerColors: Record<string, string>; // original → hex color
  editedUtterances: Record<number, string>; // index → edited text
  title: string;
}

const emptyDraft = (transcriptId: string, headerText: string): PdfDraft => ({
  transcriptId,
  headerText,
  footerText: "Generated by RecLLM",
  speakerNames: {},
  speakerColors: {},
  editedUtterances: {},
  title: "",
});

export function usePdfDraft(transcriptId: string | null, defaultHeader: string) {
  const [draft, setDraft] = useState<PdfDraft>(() =>
    emptyDraft(transcriptId || "", defaultHeader)
  );

  const resetDraft = useCallback((id: string) => {
    setDraft(emptyDraft(id, defaultHeader));
  }, [defaultHeader]);

  const updateDraft = useCallback((patch: Partial<PdfDraft>) => {
    setDraft((prev) => ({ ...prev, ...patch }));
  }, []);

  const setSpeakerName = useCallback((original: string, display: string) => {
    setDraft((prev) => ({
      ...prev,
      speakerNames: { ...prev.speakerNames, [original]: display },
    }));
  }, []);

  const setSpeakerColor = useCallback((original: string, color: string) => {
    setDraft((prev) => ({
      ...prev,
      speakerColors: { ...prev.speakerColors, [original]: color },
    }));
  }, []);

  const setUtteranceText = useCallback((index: number, text: string) => {
    setDraft((prev) => ({
      ...prev,
      editedUtterances: { ...prev.editedUtterances, [index]: text },
    }));
  }, []);

  return { draft, updateDraft, resetDraft, setSpeakerName, setSpeakerColor, setUtteranceText };
}
